# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tpr_vec <- function(splitted_classes, fpr, tpr, interpoint, ncontrols, N) {
    .Call(`_uroc_tpr_vec`, splitted_classes, fpr, tpr, interpoint, ncontrols, N)
}

